export const Colors = {
  primary: '#1B5EFF',
  primaryLight: '#EDF3FF',
  primaryBorder: '#CFE0FF',
  background: '#F5F7FC',
  backgroundAlt: '#ECF2FF',
  card: '#FFFFFF',
  cardMuted: '#F8FAFE',
  textDark: '#22314D',
  textMuted: '#7B8AA6',
  textOnPrimary: '#FFFFFF',
  border: '#E2E9F4',
  success: '#1FBF75',
  successLight: '#E7F9F0',
  warning: '#F97316',
  warningLight: '#FFF1E9',
  danger: '#E5484D',
  dangerLight: '#FFECEE',
  dangerBorder: '#FFC7CC',
  shadow: '#15264A',
};
